## Basic Configuration

baseurl = "https://www.msl09.com.br/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Marcelo Lacerda"
title = "Marcelo Lacerda"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Marcelo de Sena Lacerda (msl09)"
intro = "Backend Systems Developer"
description = "Wow, this theme makes this site looks a lot more important than it really is!"
authorImage = "headshot.jpg"
dateFormat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "My personal website"
keywords = "notmuch,tbqh"

## Social Accounts
[params.social]
github = "marceloslacerda"
#instagram = "<username>"
#linkedIn = "<username>"
#twitter = "<username>"
#facebook = "<username>"
#google = "<username>"
email = "msl09.owner@gmail.com"

## Extras
[params.extra]
copyright = "© 2016. Marcelo Lacerda. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredBy = true
hightlightJS = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
